In [ ]:
# Задача 1

import numpy as np

A = np.array([[1, 2, 1], [-2, 1, 1]])
B = np.array([[3, 1], [-1, 0], [2, 4]])
C = np.array([[-2, 2], [1, -1], [1, 2]])
A = A.transpose()

result_1 = A + 2 * B
result_2 = B + 2 * C
print('A+2B=' + '\n' + str(result_1), 'B+2C=' + '\n' + str(result_2), sep='\n\n')

A+2B=
[[7 0]
 [0 1]
 [5 9]]

B+2C=
[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [ ]:
# Задача 2

import numpy as np

matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Задача 3

import numpy as np

vector_1 = np.arange(0, 1.5, 0.1)
vector_2 = np.arange(1, 7)

matrix_1 = vector_1.reshape(5, 3)
print('matrix_1:', matrix_1, sep='\n', end='\n\n')

matrix_2 = vector_2.reshape(3, 2)
print('matrix_2:', matrix_2, sep='\n', end='\n\n')

mul_matrix = matrix_1 @ matrix_2
print('mul_matrix:', mul_matrix, sep='\n', end='\n\n')

matrix_1:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]

matrix_2:
[[1 2]
 [3 4]
 [5 6]]

mul_matrix:
[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]



In [ ]:
# Задача 4

import numpy as np

vector_a = np.arange(1, 73, 2)
vector_a1 = np.full(36, vector_a, dtype=np.int32)
print('Исходный вектор:', vector_a1, end='\n\n')

vector_b = vector_a1[1::3]
print('Вектор из исходного со значениями, кратными 3:', vector_b)


Исходный вектор: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]

Вектор из исходного со значениями, кратными 3: [ 3  9 15 21 27 33 39 45 51 57 63 69]
